### ISSUE TITLE
crash in `symbolMatches` when a production contains an <ins> tag

### ISSUE THREAD

**Issue by rbuckton** [tc39/ecmarkup#448]
I see the following crash if an SDO contains an `<emu-grammar>` with a nested `<ins>`:
```
Error: unimplemented: symbol matches ins
    at symbolMatches (C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1719:19)
    at symbolSpanMatches (C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1674:22)
    at symbolSpanMatches (C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1675:16)
    at symbolSpanMatches (C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1675:16)
    at symbolSpanMatches (C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1680:16)
    at symbolSpanMatches C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1675:16)
    at rhsMatches (C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1666:12)
    at C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1367:63
    at Array.filter (<anonymous>)
    at Spec.generateSDOMap (C:\dev\proposal-foo\node_modules\ecmarkup\lib\Spec.js:1367:51)
```

Example:

```ecmarkup
<emu-clause id="sec-foo">
  <h1>Foo</h1>
  <emu-grammar type="definition">
    Foo :
      Bar <ins>`;`</ins>
  </emu-grammar>
</emu-clause>

<emu-clause id="sec-runtime-semantics-evaluation" type="sdo">
  <h1>
    Runtime Semantics: Evaluation (
      _arg_: unknown
    )
  </h1>
  <dl class="header">
  </dl>
  <emu-grammar>
    Foo : Bar <ins>`;`</ins>
  </emu-grammar>
  <emu-alg>
    1.
  </emu-alg>
</emu-clause>
```

The only workaround is to change the `emu-grammar` in the SDO to wrap the whole production:
```ecmarkup
  <emu-grammar>
    <del>Foo : Bar</del>
    <ins>Foo : Bar `;`</ins>
  </emu-grammar>
```

**Comment by bakkot** [comment]
Thanks for the report, will fix. Fix will involve switching this logic to operate on grammarkdown nodes directly, which will avoid this problem.
